#!/bin/bash
#PBS -A m1343
#PBS -q debug
#PBS -N conf_shelf
#PBS -l mppwidth=24
#PBS -l walltime=0:20:00
#PBS -j oe

# to run, first build executables on login nodes 

export SCRIPT=confined-shelf.JFNK.config
export SCRIPT2=confined-shelf.PIC.config

# executable for parallel gnu code
export EXE=$GSCRATCH/higher-order/simple_glide_gnu

export BASE=$GSCRATCH/higher-order/confined-shelf

cd $PBS_O_WORKDIR

echo JFNK 2 proc
time aprun -n 2 $EXE  $BASE/$SCRIPT &> data/confined-shelf.out
echo PIC 2 proc
time aprun -n 2 $EXE  $BASE/$SCRIPT2 &> data/confined-shelf.outp
