#!/bin/sh
# This script needs to be run before the  cmake  command for CMake
# builds. It should be called from all cmake scripts. 
#
# This script auto-generates files that were autogerenated as part 
# of the autoconf system.

echo
echo "Auto-generating config.inc, glimmer_vers.F90, glide_io.F90, glide_lithot.F90, "
echo "glint_io.F90, glint_mbal_io.F90."
echo

mkdir -p fortran_autogen_srcs
pushd fortran_autogen_srcs
export CISM_SOURCE_DIR=../../../

# Just a copy of a file with minimal info
#pushd ..
echo "  --creating config.inc"
cp -p $CISM_SOURCE_DIR/config.inc.cmake.in $CISM_SOURCE_DIR/config.inc
#popd

# Just a copy of a file without version info
# pushd ../libglimmer
echo "  --creating glimmer_vers.F90"
cp -p $CISM_SOURCE_DIR/libglimmer/glimmer_vers.F90.cmake.in glimmer_vers.F90

# copy template file to shorten python calls below
cp $CISM_SOURCE_DIR/libglimmer/ncdf_template.F90.in .

##########################
# The following lines generate several *_io.F90 files, based on variable definition files:

# Use python scripts
echo "  --creating glide_io.F90 and glide_lithot_io.F90"
cp $CISM_SOURCE_DIR/libglide/glide_vars.def .
cp $CISM_SOURCE_DIR/libglide/glide_lithot_vars.def .
python $CISM_SOURCE_DIR/scripts/generate_ncvars.py glide_vars.def ncdf_template.F90.in
python $CISM_SOURCE_DIR/scripts/generate_ncvars.py glide_lithot_vars.def ncdf_template.F90.in

echo "  --creating glint_io.F90 and glint_mbal_io.F90 "
cp $CISM_SOURCE_DIR/libglint/glint_vars.def .
cp $CISM_SOURCE_DIR/libglint/glint_mbal_vars.def .
python $CISM_SOURCE_DIR/scripts/generate_ncvars.py glint_vars.def ncdf_template.F90.in
python $CISM_SOURCE_DIR/scripts/generate_ncvars.py glint_mbal_vars.def ncdf_template.F90.in


#echo "  --creating eis_io.F90"
#cp $CISM_SOURCE_DIR/example-drivers/eis/src/eis_vars.def .
#python ../../../scripts/generate_ncvars.py eis_vars.def ncdf_template.F90.in

echo "  --deleting temporary .def files and template file"
rm *.def
rm ncdf_template.F90.in

popd


