#!/bin/bash
#PBS -A m1343
#PBS -q regular
#PBS -N ismip_hom_c
#PBS -l mppwidth=24
#PBS -j oe 
#PBS -l walltime=1:00:00

# to run, first build executables on login nodes 

export SCRIPT2=ishom.c.80km.PIC.config
export SCRIPT3=ishom.c.80km.JFNK.trilinos.config
export SCRIPT4=ishom.c.80km.PIC.trilinos.config

# executable for parallel code
export EXE=$GSCRATCH/higher-order/simple_glide_serial
export EXE2=$GSCRATCH/higher-order/simple_glide_gnu

export BASE=$GSCRATCH/higher-order/ismip-hom-c

cd $PBS_O_WORKDIR

echo PIC serial
time aprun -n1 $EXE  $BASE/$SCRIPT2 &> data/ishom.c.80km.outp.s

echo JFNK 1 proc
time aprun -n1 $EXE2  $BASE/$SCRIPT3 &> data/ishom.c.80km.out.1
echo PIC 1 proc
time aprun -n1 $EXE2  $BASE/$SCRIPT4 &> data/ishom.c.80km.outp.1

echo JFNK 2 proc
time aprun -n2 $EXE2  $BASE/$SCRIPT3 &> data/ishom.c.80km.out.2
echo PIC 2 proc
time aprun -n2 $EXE2  $BASE/$SCRIPT4 &> data/ishom.c.80km.outp.2

echo JFNK 4 proc
time aprun -n4 $EXE2  $BASE/$SCRIPT3 &> data/ishom.c.80km.out.4
echo PIC 4 proc
time aprun -n4 $EXE2  $BASE/$SCRIPT4 &> data/ishom.c.80km.outp.4
