#!/bin/bash
#PBS -A m1343
#PBS -q debug
#PBS -N dome_30_test
#PBS -l mppwidth=24
#PBS -l walltime=0:10:00
#PBS -j oe

# to run, first build executables on login nodes in serial and parallel
# and make

export SCRIPT=dome.30.JFNK.trilinos.config
export SCRIPT1a=dome.30.JFNK.trilinos.config.1
export SCRIPT1b=dome.30.JFNK.trilinos.config.4
export SCRIPT2=dome.30.PIC.trilinos.config
export SCRIPT3=dome.30.JFNK.slap.config
export SCRIPT4=dome.30.PIC.slap.config

# executable for parallel code
export EXE=$GSCRATCH/higher-order/simple_glide_gnu
export EXE2=$GSCRATCH/higher-order/simple_glide_pgi
# executable for serial code
export EXE3=$GSCRATCH/higher-order/simple_glide_serial

export BASE=$GSCRATCH/higher-order/reg_test/dome30/diagnostic/

cd $PBS_O_WORKDIR

echo GNU JFNK 1 proc
time aprun -n 1 $EXE  $BASE/$SCRIPT1a  &> data/gnu.JFNK.1proc
echo GNU JFNK 4 proc
time aprun -n 4 $EXE  $BASE/$SCRIPT1b  &> data/gnu.JFNK.4proc

echo PGI JFNK 1 proc
time aprun -n 1 $EXE2  $BASE/$SCRIPT  &> data/pgi.JFNK.1proc
echo PGI JFNK 4 proc
time aprun -n 4 $EXE2  $BASE/$SCRIPT  &> data/pgi.JFNK.4proc

echo PIC 1 proc
time aprun -n 1 $EXE  $BASE/$SCRIPT2  &> data/gnu.PIC.1proc
echo PIC 4 proc
time aprun -n 4 $EXE  $BASE/$SCRIPT2 &> data/gnu.PIC.4proc

echo JFNK slap
time aprun -n 1 $EXE3  $BASE/$SCRIPT3  &> data/out.JFNK.slap
echo PICARD slap
time aprun -n 1 $EXE3  $BASE/$SCRIPT4  &> data/out.PIC.slap
